### ISSUE TITLE
Adjust design according to artboards

### ISSUE THREAD

**Issue by cube5** [DIYbiosphere/diybiosphere.github.io.old#3]
The current design will be readjusted to match the current (and coolest 🤘) artboards.

**Comment by sabgaby** [comment]
We are in the process of hiring a professional designer! So this should wait a bit!!!

**Comment by cube5** [comment]
Nice! no problem I'll drag it in To Do's pipeline

**Comment by cube5** [comment]
Issue moved to [DIYbiosphere/diybiosphere.io #4](https://github.com/DIYbiosphere/diybiosphere.io/issues/4) via [**ZenHub.io**](https://www.zenhub.io/)
