### ISSUE TITLE
sass folder and files

### ISSUE THREAD

**Issue by sabgaby** [DIYbiosphere/diybiosphere.github.io.old#9]
hey @cube5, do you think we could code the style in sass instead of css? It's easier to write and read

**Comment by cube5** [comment]
I agree, no problem :ok_hand:

**Comment by cube5** [comment]
Issue moved to [DIYbiosphere/diybiosphere.io #8](https://github.com/DIYbiosphere/diybiosphere.io/issues/8) via [**ZenHub.io**](https://www.zenhub.io/)
